### ISSUE TITLE
Configuration file to manage multiple WebHooks

### ISSUE THREAD

**Issue by FinweVI** [benjojo/alertmanager-discord#10]
Hello,

if we want to send alerts to various Discord Channels, each Channel having it's own WebHook, we have to run multiple instances of `alertmanager-discord`.

It could be nice to have a YAML configuration file storing endpoints and WebHooks.

For instance:

```yaml
webhooks:
  - name: "channel1"
    webhook: "https://discord.com/api/webhooks/..."
  - name: "channel2"
    webhook: "https://discord.com/api/webhooks/..."
```
With `alertmanager-discord` having a routed endpoint on `http://127.0.01:9094/channel1` and `http://127.0.01:9094/channel2`.

This would allow to send alerts to an infinite amount of channels with only one running daemon.

My Go is not top-nocht but I'm willing to try for a PR if there's any chance for it to be accepted.
