### ISSUE TITLE
Error on alert - cannot unmarshal array into Go value of type main.alertManOut

### ISSUE THREAD

**Issue by sfoxdev** [benjojo/alertmanager-discord#18]
Using docker image `benjojo/alertmanager-discord:latest`
Runs with Prometheus 2.24.0 and Grafana 7.3.6.

On alert getting such error:
```
2021/02/17 16:03:29 Listening on: 0.0.0.0:9094
2021/02/17 16:03:52 http: panic serving 10.0.8.4:57922: json: cannot unmarshal array into Go value of type main.alertManOut
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc00006ebe0)
        /usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x6dd0c0, 0xc00004c230)
        /usr/local/go/src/runtime/panic.go:975 +0x47a
main.main.func1(0x79a560, 0xc0000b80e0, 0xc0000ac100)
        /go/src/mypackage/myapp/main.go:110 +0xd54
net/http.HandlerFunc.ServeHTTP(0xc000040c90, 0x79a560, 0xc0000b80e0, 0xc0000ac100)
        /usr/local/go/src/net/http/server.go:2042 +0x44
net/http.serverHandler.ServeHTTP(0xc0000b8000, 0x79a560, 0xc0000b80e0, 0xc0000ac100)
        /usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc00006ebe0, 0x79ab60, 0xc000010500)
        /usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2969 +0x36c
2021/02/17 16:03:52 http: panic serving 10.0.8.4:57924: json: cannot unmarshal array into Go value of type main.alertManOut
```

**Comment by benjojo** [comment]
What is your configuration for alert manager or anything else sending
things to that container?

**Comment by sfoxdev** [comment]
Here is config file
```
global:
  resolve_timeout: 1m

route:
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 30m
  receiver: 'discord'

receivers:
  - name: 'discord'
    webhook_configs:
    - url: 'http://localhost:9094'
```
