### ISSUE TITLE
Alerts doesn't send to discord

### ISSUE THREAD

**Issue by haosb** [benjojo/alertmanager-discord#36]
Hello,
I have Alertmanager, Prometheus and the discord-webhook, I think pinned configs are right, but zero alerts in discord. When alert in a fired state alertmanager-discord took POST request in logs. I have no idea how to fix.

![image](https://user-images.githubusercontent.com/114342765/202302873-c689095d-9f8b-4c9c-9c1c-f8d4c1bedf8f.png)
![image](https://user-images.githubusercontent.com/114342765/202302945-b1547116-aaba-4065-8dc0-6499520df553.png)

This is my alertmanager config:
```
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: discord
      group_by: ['alertname']
      group_wait: 10s
      repeat_interval: 30m
 
    receivers:
    - name: discord
      webhook_configs:
      - url: 'http://alertmanager-discord.newmonitoring:9094'
        send_resolved: true
```
This is Alertmanager-discord deployment:
```
omitted..
      - name: alertmanager-discord
        image: benjojo/alertmanager-discord
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9094
        env:
          - name: DISCORD_WEBHOOK
            value: 'https://discord.com/api/webhooks/...'
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-discord
  namespace: newmonitoring
spec:
  selector:
    app: alertmanager-discord
  ports:
  - port: 9094
    targetPort: 9094
  type: ClusterIP
```

And this prometheus config with rule what I should to see:

```
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: up > 0
        for: 1m
        annotations:
          summary: High Memory Usage

  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.newmonitoring.svc:9093"
```
